services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev -- --entryFile worker
    environment:
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=${REDIS_URL}
    networks:
      - shared-network
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src
          ignore:
            - node_modules/
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild

networks:
  shared-network:
    external: true
